name: Fetch Weekly

on:
  schedule:
  - cron: '0 1,13 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Clone the prarxivate repo
      run: |
        git clone https://github.com/GzuPark/prarxivate.git
        cp automation.py prarxivate/automation.py
    - name: Install python packages
      run: |
        cd prarxivate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dropbox
    - name: Download db from dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
      run: |
        cd prarxivate
        python -c 'from automation import download_db; download_db();'
    - name: Fetch 500 papers from arXiv
      run: |
        cd prarxivate
        python fetch_papers.py -si 5000 -mi 10000 -break 0 --wait-time 10 -sq cat:cs.CV+OR+cat:cs.RO+OR+cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CL+OR+cat:cs.NE+OR+cat:stat.ML
    - name: Upload db to dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
      run: |
        cd prarxivate
        python -c 'from automation import upload_db; upload_db();'
