name: Fetch Daily

on:
  schedule:
  - cron: '0 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Submodule init
      run: |
        git submodule init
        git submodule update
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r prarxivate/requirements.txt
        pip install dropbox
    - name: Download db from dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
      run: |
        python -c 'from automation import download_db; download_db();'
    - name: Fetch 1000 papers from arXiv
      run: |
        python prarxivate/fetch_papers.py -mi 1000 -break 0 -sq cat:cs.CV+OR+cat:cs.RO+OR+cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CL+OR+cat:cs.NE+OR+cat:stat.ML
    - name: Upload db to dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
      run: |
        python -c 'from automation import upload_db; upload_db();'
