name: Report test

on:
  schedule:
  - cron: '5/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Submodule init
      run: |
        git submodule init
        git submodule update --remote --merge
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r prarxivate/requirements.txt
        pip install dropbox
    - name: Download db from dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
      run: |
        python -c 'from automation import download_db; download_db();'
    - name: Make reports & Upload reports to dropbox
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DB_PATH: ${{ secrets.DB_PATH }}
        REPORT_PATH: ${{ secrets.REPORT_PATH }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER1: ${{ secrets.EMAIL_RECEIVER1 }}
        EMAIL_RECEIVER2: ${{ secrets.EMAIL_RECEIVER2 }}
      run: |
        export FROM_DATE=$(date "+%Y-%m-%d")
        echo "Start $FROM_DATE"
        export TO_DATE=$(date "+%Y-%m-%d" -d "-4 days")
        echo "To $TO_DATE"
        python prarxivate/make_report.py -d "$FROM_DATE $TO_DATE" -ds u
        python send_email.py -id $EMAIL_SENDER -pw $EMAIL_PASSWORD -to $EMAIL_RECEIVER2
        python prarxivate/make_report.py -d "$FROM_DATE $TO_DATE" -ds u -c cs.CV
        python prarxivate/make_report.py -d "$FROM_DATE $TO_DATE" -ds u -c cs.CV+cs.RO
        echo "Done"
